services:
  postgres:
    image: postgres:16-alpine
    container_name: livro_cia_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"] # log everything
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - livro_e_cia_network

volumes:
  postgres_data:
    name: livro_e_cia_postgres

networks:
  livro_e_cia_network:
    name: livro_e_cia_network
    driver: bridge
